version: '3.1'

services:
  db:
    container_name: exampledb
    image: mysql
    restart: always
    ports:
      - 3306:3306
    environment:
      MYSQL_ROOT_PASSWORD: secretpw
      MYSQL_DATABASE: mydb
